backend:
  name: github
  repo: lizfaria/Portfolio-2020
media_folder: static/assets
public_folder: static/assets
collections:
  - label: "Pages"
    name: "pages"
    files:
      - name: home
        label: Home
        file: src/markdown-pages/collection/home.md
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: home }
          - {label: Title, name: title, widget: string}
          - {label: OverTitle, name: overtitle, widget: string}
          - {label: Headshot, name: headshot, widget: image}
          - {label: Logo, name: logo, widget: image}
          - {name: body, label: Body, widget: markdown }
          - {name: resume, label: Resume, widget: file }
      - name: contact
        label: Contact
        file: src/markdown-pages/collection/contact.md
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: contact }
          - {label: Title, name: title, widget: string}
          - label: Links
            name: links
            widget: list
            fields: 
            - {label: Image, name: image, widget: image}
            - {label: Image Alt, name: imageAlt, widget: string}
            - {label: text, name: text, widget: string}
            - {label: url, name: url, widget: string}
      - name: portfolio
        label: Portfolio
        file: src/markdown-pages/collection/portfolio.md
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: portfolio }
          - {label: Title, name: title, widget: string}
          - { name: body, label: Body, widget: markdown }
          - label: Projects
            name: projects
            widget: list
            fields: 
            - {label: Title, name: text, widget: string}
            - {label: Subtitle, name: subtitle, widget: string}
            - {label: Image, name: image, widget: image}
            - {label: Image Alt, name: imageAlt, widget: string}
            - {label: text, name: text, widget: body}
            - label: Links
              name: links
              widget: list
              - {label: url, name: url, widget: string}
              - {label: text, name: text, widget: string}
      - name: skills
        label: Skills
        file: src/markdown-pages/collection/skills.md
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: skills }
          - {label: Title, name: title, widget: string}
          - label: Skills List
            name: skills-list
            widget: list
            fields: 
            - {label: text, name: text, widget: string}